# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0006_auto_20161113_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='First_Name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='Last_Name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='Zipcode',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='Phone_number',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='School',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='Work',
            new_name='work',
        ),
        migrations.RenameField(
            model_name='bookleaseuser',
            old_name='password',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='bookleaseuser',
            name='Email_address',
        ),
        migrations.AddField(
            model_name='bookleaseuser',
            name='agreetermsandconditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookleaseuser',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
