# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0015_auto_20161120_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
