# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 23:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('edition', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('book_status', models.CharField(choices=[('AV', 'Available'), ('OH', 'On Hold'), ('RE', 'Rented')], default='AV', max_length=2)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('book_status', models.CharField(choices=[('AV', 'Available'), ('OH', 'On Hold'), ('RE', 'Rented')], default='RE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('Zipcode', models.CharField(max_length=15)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Gender', models.BooleanField()),
                ('School', models.CharField(max_length=30)),
                ('Work', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to='booklease.User'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_for', to='booklease.User'),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='book_borrowed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_by', to='booklease.User'),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='borrowed_book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_name', to='booklease.Book'),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='borrowed_book_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_owner', to='booklease.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklease.User'),
        ),
    ]
