# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0007_auto_20161113_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookleaseuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookleaseuser',
            name='username',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
