# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0013_remove_borrowedbook_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='borrowed_book_name',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='borrowed_book_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_id', to='booklease.Book'),
            preserve_default=False,
        ),
    ]
