# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0003_auto_20161106_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='booklease/images/'),
        ),
    ]
