# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0005_auto_20161106_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLeaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=30)),
                ('Zipcode', models.CharField(max_length=15)),
                ('Phone_number', models.CharField(max_length=30)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('School', models.CharField(max_length=30)),
                ('Work', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='book_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklease.BookLeaseUser'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='book_borrowed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_by', to='booklease.BookLeaseUser'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_book_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book_owner', to='booklease.BookLeaseUser'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to='booklease.BookLeaseUser'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_for', to='booklease.BookLeaseUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
