# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0009_auto_20161113_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklease.BookLeaseUser'),
        ),
    ]
