# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0012_bookrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book_status',
        ),
    ]
