# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklease', '0017_borrowedbook_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='review_id', to='booklease.BorrowedBook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
